---
title: "BA - DEA"
output: html_notebook
---

# load libraries

```{r}
library(tidyverse)
library(deaR)
library(ggplot2)
library(countrycode)

```

# Preparation

## Select data to be used and set parameter

```{r}
# Chose the attempt
attempt = 11

# Number of in- and outputs -> checl struture of selected data set!
number_of_inputs <- 2
number_of_outputs <- 3

# only from 1990?
from_1990 <- "no"

# only one year?
only_one_year <- 0 # 0 means no

# only one country?
only_one_country <- "" # empty string means no

orientation <- "io"
# io: input oriented
# oo: output oriented

return_to_scale <- "vrs"
# crs: constant return to scale
# vrs: variable return to scale
# nirs: non-increasing
# ndrs: non-decreasing
# grs: generalized
```

## Load data

```{r}
data = read_csv(paste("D:/Daten/Bildung/HS Mannheim/BA/bachelors-thesis/processed_data/final_", as.character(attempt), ".csv", sep = ""), show_col_types = FALSE)
str(data)
```

### Apply chosen selection

```{r}

if (from_1990 != "no") {
  data <- data %>%
    filter(year >= 1990)
}

if (only_one_year != 0) {
  data <- data %>%
    filter(year == only_one_year)
}

if (only_one_country != "") {
  data <- data %>%
    filter(country == only_one_country)
}
  
```

## Combine country and year to one string to use it as a name for the DMUs

```{r}
data$dmu <- str_c(data$country, "_", data$year)
data$country <- NULL
data$year <- NULL
data <- data %>% relocate(dmu)
```

# DEA

```{r}

# Documentation: https://cran.r-project.org/web/packages/deaR/deaR.pdf

model_data <- read_data(data, ni=number_of_inputs, no=number_of_outputs, dmus = 1)

result <- model_basic(model_data, orientation = orientation, rts=return_to_scale)
```

## Efficiencies and Targets

```{r}
# Efficiencies
eff <- as.data.frame(efficiencies(result))
# add column for dmu names
eff$dmu <- rownames(eff)
# delete rownames
rownames(eff) <- NULL
# Rename efficiency column
colnames(eff)[1] <- "efficiencies"

# get targets
targets <- as.data.frame(targets(result))
# add column for dmu names
targets$dmu <- rownames(targets)
# delte rownames
rownames(targets) <- NULL
```

## Merge all together

```{r}
data_and_results <- list(
  data,
  eff,
  targets
)

data_dea <- data_and_results %>% reduce(full_join, by="dmu")
```

```{r}
data_dea <- data_dea %>% relocate(efficiencies, .after = dmu)
```

## Split um dmu column to country and year but keep dmu column

```{r}
data_dea <- separate(data_dea, dmu, c("country", "year"), "_", remove=FALSE)
```

## Add contintents

```{r}
data_dea$continent <- countrycode(sourcevar = data_dea$country,
                               origin = "country.name",
                               destination = "continent")
```

## export as csv

```{r}
write_csv(data_dea, paste("D:/Daten/Bildung/HS Mannheim/BA/bachelors-thesis/processed_data/dea_results_", as.character(attempt), "_", orientation, "_", return_to_scale, ".csv", sep = ""))
```
