---
title: "BA - Visualization"
output: html_notebook
---

## load libraries

```{r}
library(tidyverse)
library(ggplot2)
```

## load data

```{r}
filename <- "dea_results_15_io_vrs_Germany.csv"

data <- read_csv(paste("D:/Daten/Bildung/HS Mannheim/BA/bachelors-thesis/processed_data/", filename, sep = ""), show_col_types = FALSE)
```

## Some stats
```{r}
summary(data)
```

## years vs effiviency

```{r}
data %>%
  filter(continent == "Europe") %>%
  ggplot(aes(year, efficiencies))+
  geom_line(aes(
    color=country
  ))
```
## Efficienies per continent (all years)

```{r}
data %>%
  # filter(continent == "Africa") %>%
  filter(year %in% c(2000:2010)) %>%

  ggplot(aes(continent, efficiencies))+
  geom_boxplot()+
  geom_jitter(width = 0.1,
              alpha = 0.5,
              aes(
                color=year
              )
              )
```


```{r}

data %>%
  # filter(continent == "Africa") %>%
  filter(year %in% c(2010:2020)) %>%

  ggplot(aes(continent, efficiencies))+
  geom_boxplot()+
  geom_jitter(width = 0.1,
              alpha = 0.5,
              aes(
                color=year
              )
              )


```

